Delete uploads file
Got an error when checkout main branch, need to delete these files

```
error: invalid path 'uploads/<Project_B.pdf>-1706124784142-516723496'
error: invalid path 'uploads/<opt.pdf>-1706118678510-549823656'
error: invalid path 'uploads/<opt.pdf>-1706125620540-775361754'
```